---
title: "SRTsim_redesign"
output: html_notebook
---

```{r, include=TRUE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries loading}
source('SRT_functions.R')
library('SRTsim')
```

```{r fitting}
## Set a seed for reproducible simulation
set.seed(seed)

## Estimate model parameters for data generation
simSRT_fit <- srtsim_fit(simSRT, sim_schem="domain")
```

## Pure tumors
```{r, eval=FALSE}
simSRT_fit@refcolData$target_label[simSRT_fit@refcolData$label %in% c("basal", 'other', "classical and basal")] <- "other"
simSRT_fit@refcolData$target_label[simSRT_fit@refcolData$label =="classical"] <- "classical"
```

## Mixed Tumors

```{r, eval=FALSE}

simSRT_fit@refcolData$target_label <- 'other' #Initialisation

simSRT_fit@refcolData[rownames(simSRT_fit@refcolData) %in% krt6a_pos,]$target_label <- 'basal'
simSRT_fit@refcolData[rownames(simSRT_fit@refcolData) %in% fam83a_pos,]$target_label <- 'classical'
simSRT_fit@refcolData[rownames(simSRT_fit@refcolData) %in% intersect(krt6a_pos, fam83a_pos),]$target_label<- 'classical and basal'

#simSRT_fit@refcolData$target_label
```

```{r, eval=FALSE}
redesign_visualisation(simSRT_fit@refcolData)
```

```{r, eval=FALSE}
#Redesign
#spatial expression pattern of other (ref) --> to other (sim)
#Rappel: target label contains the same number of element that wished domains
simSRT_affine <- srtsim_count_affine(simSRT_fit, reflabel= c('basal', 'other'), targetlabel = c('basal', 'other'), nn_func = 'ransam' )
``` 

```{r, eval=FALSE}
compare_ref_sim('basal_UCell', simSRT_affine)
```

```{r, eval=FALSE}
compare_ref_sim('classical_UCell', simSRT_affine)
```

# Csv file Writing (simulated counts)
```{r}
write.csv(t(simSRT_count@simCounts), paste0(output_dir, '/', sample_name, '_', seed,'.csv'))
```